flyteorg/flyte-sdk

examples/advanced/large_inline_io.py
examples/code-runner/code_runner_agent.py
examples/genai/agent_simulation_loadtest.py
examples/genai/openai_agents/tools.py
examples/genai/trading_agents/main.py
src/flyte/_internal/controllers/__init__.py
src/flyte/_internal/controllers/_local_controller.py
src/flyte/_internal/controllers/remote/_controller.py
src/flyte/_internal/runtime/io.py
src/flyte/_task.py
src/flyte/_task_environment.py
src/flyte/errors.py
src/flyte/extras/_container.py
src/flyte/models.py
src/flyte/remote/_task.py
tests/internal/controllers/test_remote_controller.py
tests/unit/test_runtime_io.py

- prevents uploading very large inputs or downloading large outputs
- This can be overriden at runtime
- This can also be set per task at declaration time
```python
import flyte
env = flyte.TaskEnvironment("x")
@env.task(max_inline_io_bytes=100*1024*1024)
async def foo():
...
@env.task
async def main():
await foo.with_overrides(max_inline_io_bytes=1)()
```

Protects Driver memory

---

src/flyte/_internal/runtime/convert.py
src/flyte/models.py
tests/flyte/internal/runtime/test_convert.py

If the input names mismatch the required inputs, we should raise an error as well
Before:
```
File "/Users/kevin/git/flyte-sdk/src/flyte/_internal/runtime/entrypoints.py", line 39, in direct_dispatch
return await contextual_run(
^^^^^^^^^^^^^^^^^^^^^
File "/Users/kevin/git/flyte-sdk/src/flyte/_context.py", line 152, in contextual_run
return await _ctx.run(func, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/kevin/git/flyte-sdk/src/flyte/_internal/runtime/taskrunner.py", line 142, in convert_and_run
inputs_kwargs = await convert_inputs_to_native(inputs, task.native_interface)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/kevin/git/flyte-sdk/src/flyte/_internal/runtime/convert.py", line 57, in convert_inputs_to_native
native_vals = await …
```

refactor(runtime): improve required inputs validation logic

---

src/flyte/cli/_create.py
src/flyte/cli/_option.py
tests/cli/test_create.py

This PR aligns the actual implementation of `flyte create secret` with the docstring. Users need to supply a secret `--value` flag, and if not provided, an input prompt that hides the password value is shown to the user.

improve secrets cli: add validation, provide secret value through input

---

examples/genai/langgraph_agent.py
src/flyte/cli/_build.py
src/flyte/cli/_common.py
src/flyte/cli/_deploy.py
src/flyte/cli/_get.py
src/flyte/cli/_run.py
src/flyte/cli/main.py
src/flyte/remote/_action.py
src/flyte/remote/_common.py
src/flyte/remote/_project.py
src/flyte/remote/_run.py
src/flyte/remote/_secret.py
src/flyte/remote/_task.py

This pull request introduces significant improvements to the Flyte CLI and SDK around output formatting and JSON serialization. The goal is to make CLI output more flexible, scriptable, and user-friendly, especially for automation and integration with other tools.
---
**1. Output Format Option for CLI**
- Replaces the boolean --simple flag with a new --output-format (or -of) option.
- Supports multiple formats: table (default), table-simple, and json.
- All CLI commands that previously used get_table now use the new format function, allowing consistent output formatting based on user preference.
**2. Common Formatting Utilities**
- Introduces a new format function in _common.py that handles table, simple table, and JSON output for iterable objects.
- get_panel is updated to respect output …

Making every command output json (In the future yaml too)

---

examples/advanced/container_task.py
examples/plugins/ray_example.py
examples/plugins/spark_example.py
src/flyte/_image.py
src/flyte/_internal/imagebuild/remote_builder.py
src/flyte/_run.py
src/flyte/remote/_task.py
tests/user_api/test_override.py

```python
import flyte
from flyte import remote
from flyte.extras import ContainerTask
env = flyte.TaskEnvironment(name="hello_world")
greeting_task = ContainerTask(
name="echo_and_return_greeting",
image="alpine:latest",
input_data_dir="/var/inputs",
output_data_dir="/var/outputs",
inputs={"name": str},
outputs={"greeting": str},
command=["/bin/sh", "-c", "echo 'Hello, my name is {{.inputs.name}}.' | tee -a /var/outputs/greeting"],
)
env.add_task(greeting_task)
@env.task
async def say_hello(name: str = "flyte") -> str:
print("Hello container task")
return await greeting_task(name=name)
if __name__ == "__main__":
import flyte.storage
flyte.init_from_config("../../config.yaml")
entity = remote.Task.get(
name="echo_and_return_greeting",
project="flytesnacks",
domain="development", …
```

Add support override in LazyEntity

---

examples/basics/hello_v2.py
src/flyte/cli/_common.py
src/flyte/cli/_run.py
src/flyte/remote/_task.py

This PR adds support for running reference tasks from the cli with:
```bash
flyte run reference-task <task-name> --arg1 foo --arg2 bar
```
This also modifies the `flyte run` file commands so that it's relative to the current working directory:
```
flyte run 
╭─ Commands ───────────────────────────────────────────────────────────────────────────────────────────╮
│ reference-task         Run reference task 'reference-task' from the Flyte backend                    │
│ exception_handling.py  Run functions decorated with env.task in exception_handling.py                │
│ hello.py               Run functions decorated with env.task in hello.py                             │
│ report_example.py      Run functions decorated with env.task in report_example.py                    │
│ devbox_one.py …
```

Add support for running reference tasks

---

src/flyte/cli/_common.py
src/flyte/cli/_run.py

This PR renames `flyte run reference-task` to `flyte run deployed-task` to be more consistent and ergonomic with the way this command will be used:
- When I do `flyte run deploy ...`
- Then, naturally I want to do `flyte run deployed-task ...`
Also mode the `deployed-task` command from the `FileGroup` class into the `TaskFiles` class.

rename command to flyte run deployed-task

---

examples/basics/hello_polyglot.py
src/flyte/__init__.py
src/flyte/_initialize.py
src/flyte/_logging.py
src/flyte/_run.py
src/flyte/cli/_run.py
src/flyte/remote/_client/auth/_channel.py
src/flyte/remote/_client/controlplane.py

- This can be removed once the entire code is rustified.
These logs are now gone!
```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1755442414.463529  826985 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0000 00:00:1755442414.830864  826985 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
```

Removes the grpc warning messages.

---

examples/image/image_from_env.py
src/flyte/types/_type_engine.py
tests/flyte/internal/runtime/test_convert.py

TypeStructure for pydantic was for propeller attribute access.  Attribute access now happens in propeller.  Was leaving it in for future dag work but we can bring it back (correctly) if & when that comes to pass.

Nix pydantic & dataclass type structure

---

examples/image/image_from_env.py
src/flyte/_secret.py
tests/flyte/internal/runtime/test_task_serde.py

This pull request introduces improvements to secret handling and environment variable naming conventions, updates documentation and examples for clarity, and refines related tests to match the new behavior. The main focus is on standardizing how secrets are exposed as environment variables and improving usability for developers.
* Updated the logic in the `Secret` class so that if neither `mount` nor `as_env_var` is specified, the environment variable name is automatically generated by combining the group and key, replacing hyphens with underscores, and converting to uppercase (e.g., `"my-secret"` becomes `"MY_SECRET"`). This ensures consistency and reduces manual configuration.
* Changed the default mounting behavior for secrets to use environment variables (`ENV_VAR`) instead of files, …

Fix secret

---

examples/stress/long_running.py
examples/stress/long_running_reuse.py
plugins/spark/src/flyteplugins/spark/task.py
plugins/spark/tests/test_task.py
src/flyte/_pod.py
src/flyte/models.py

This pull request introduces improvements and fixes for Spark task configuration, testing, and code organization. The most significant changes include enhancements to the Spark plugin's configuration logic, the addition of comprehensive tests for Spark tasks, and refactoring for better code clarity and maintainability.
* Updated `custom_config` in `Spark` to provide sensible defaults for `mainApplicationFile` and `executorPath` when not explicitly set, using the serialization context to determine these paths. This ensures more robust and predictable Spark job configuration.
* Refactored the `SerializationContext` class to introduce an `interpreter_path` field and improved the logic for determining the entrypoint path, making path resolution clearer and more flexible.
* Added new tests in …

Add a default interpreter_path and entrypoint_path

---

src/flyte/remote/_action.py

It will improve the error messages for the remote builder
Before:
After:

fix: Use error_info.message for clearer error msgs

---

examples/image/uv_project.py
examples/plugins/spark_example.py
src/flyte/_image.py
src/flyte/_internal/imagebuild/docker_builder.py
src/flyte/_internal/imagebuild/remote_builder.py
src/flyte/_internal/imagebuild/utils.py

This pull request makes two important updates to the `src/flyte/_internal/imagebuild/remote_builder.py` file, improving how files are copied to the build context and correcting the default secret directory path for image builds.
Improvements to file handling in layer definition:
* Updated `_get_layers_proto` to use the `copy_files_to_context` function for copying `pyproject` and `uvlock` files, ensuring files are properly placed in the build context and referenced relative to it. Also, added support for `options` and `secret_mounts` in the layer definition.
Fix to secret directory path:
* Changed the default secret directory path from `"etc/flyte/secrets"` to `"/etc/flyte/secrets"` in `_get_build_secrets_from_image`, ensuring secrets are mounted from the correct location.

with_uv_project for remote builder

---

examples/deploy_patterns/pyproject/pyproject.toml
examples/deploy_patterns/pyproject/pyproject_test.py
examples/deploy_patterns/pyproject/uv.lock

As a user, I want to install optional dependencies in my `uv.lock` file.
Given the following `pyproject.toml` file:
```toml
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
"flyte>=2.0.0b17",
"requests",
"numpy",
]
[project.optional-dependencies]
pandas = ["pandas"]
```
I want to install the `pandas` optional dependency
```
flyte.Image.from_debian_base(registry="docker.io/nielsbantilan").
with_uv_project(
pyproject_file=pathlib.Path("pyproject.toml"),
extras=["pandas"],
pre=True,
)
```

with_uv_project doesnt support extras in uv.lock

---

.gitignore
src/flyte/_code_bundle/_packaging.py
src/flyte/_deploy.py
src/flyte/_initialize.py
src/flyte/_internal/imagebuild/remote_builder.py
src/flyte/_logging.py
src/flyte/remote/_client/auth/_authenticators/device_code.py
src/flyte/remote/_data.py

This PR updates `logging` and `click.secho` statements to use rich so that it all looks good on a terminal and jupyter notebook.
Terminal:
Jupyter notebook (before):
Jupyter notebook (after):

update logger rich styling to work on terminal and jupyter

---

.github/workflows/publish.yml

• Adds wait logic for flyte-pypi package availability in CI workflow
• Ensures builds wait for package publishing to complete before proceeding

Wait for flyte-pypi package availability before building

---

src/flyte/_task.py

Changed the default value of the `cache` parameter in the `TaskTemplate from `"auto"` to `"disable"`, which means all tasks will no longer be cached by default.

Disable cache for raw container task by default

---

src/flyte/_debug/constants.py
src/flyte/_run.py

- Remove Jupyter extension from default code server extensions to reduce startup time
- Prevent overriding existing LOG_LEVEL environment variables in runner

Reduce startup overhead for the debug button

---

src/flyte/_internal/imagebuild/docker_builder.py
tests/flyte/imagebuild/test_docker_builder.py

This PR includes a bug fix in how secret env vars are added to the docker build command - the format should be `--secret id=<SOME_ID>,env=<ENV_VAR_NAME>` however currently `env=<ENV_VAR_VALUE>`.
Additionally, we add support for the `CommandsHandler` to pass secret mounts given the commands layer can accept those as arguments - it is also useful to run commands with some secret mounted.

Allow local builder's command to use mounted secrets, fix secret command generation from env vars

---

examples/advanced/container_task.py
examples/basics/using_dockerfiles.py
src/flyte/_internal/imagebuild/remote_builder.py
src/flyte/_task_environment.py
tests/user_api/test_task_environment.py

```python
tk = flyte.ContainerTask(...)
env = flyte.from_tasks("my_env", tk)
```
This makes it consistent that everytime a Object task is created it can be added to an environment and every environment has one and only one image
All Environments will now have one image and only one image. An environment has some common properties and 3 most important ones are 
1. Name,
2. Image
3. Depends_on
ImageCache is just a list of images per environment now.

[Breaking] Removes the need for `add_task` in TaskEnvironment

---

examples/deploy_patterns/pyproject/pyproject_test.py
examples/deploy_patterns/uv_workspace/src/workflows/albatross.py
examples/deploy_patterns/uv_workspace/uv.lock
src/flyte/_deploy.py
src/flyte/_image.py
src/flyte/_internal/imagebuild/docker_builder.py
tests/flyte/imagebuild/test_docker_builder.py

- Improves hash calculation for UV and Poetry project layers by hashing source code when project installation is enabled
- Adds `--inexact` flag to uv sync commands for better reliability  
- Cleans up unused imports in _deploy.py
- **UVProject**: Now hashes the entire source directory when `--no-install-project` is not in extra_args, otherwise hashes just the lock and pyproject files
- **PoetryProject**: Similar logic - hashes source directory when `--no-root` is not in extra_args
- **Docker templates**: Added `--inexact` flag to uv sync commands for more robust dependency resolution
- **Code cleanup**: Removed unused imports in _deploy.py

Improve hash calculation for UV and Poetry project layers

---

examples/basics/devbox_one.py
examples/plugins/ray_example.py
src/flyte/cli/_params.py
tests/cli/test_params.py

click option parsing wasn't correct for boolean flags that are on by default.  These need a `--no` variant of the flag.
can test with
```python
@env.task
async def flag_example(
flag: bool, normally_off: bool = False, normally_on: bool = True, optional: bool | None = None
) -> str:
print(f"Args: {flag=}, {normally_off=}, {normally_on=}, {optional=}")
return f"flag: {flag}, normally_off: {normally_off}, normally_on: {normally_on}, optional: {optional}"
```

Allow cli to turn off default on flags

---

examples/basics/dataframe_usage.py
examples/basics/dir.py
examples/basics/dir_sync.py
examples/basics/file.py
examples/basics/sync_file.py
examples/stress/large_file_io.py
examples/stress/rewrite_example.py
src/flyte/_internal/runtime/taskrunner.py
src/flyte/_logging.py
src/flyte/errors.py
src/flyte/io/_dir.py
src/flyte/io/_file.py
src/flyte/storage/__init__.py
src/flyte/storage/_storage.py
tests/flyte/io_types/test_files.py
tests/flyte/type_engine/pydantic/test_pydantic_basemodel_transformer.py
tests/internal/storage/test_storage.py

The File API is changed.
open now always returns an async file handle in async mode. open_sync returns a sync file handle.
open, fh.read, returns a memoryview, which has to be type casted to `bytes`. 
@wild-endeavor shall we modify it somehow to make it `bytes`? Memory view is faster

**Breaking** flyte.io.File sync/async api and Faster data

---

src/flyte/_excepthook.py
tests/flyte/test_excepthook.py

- Improve traceback formatting by using `traceback.print_tb()` instead of manual string formatting
- Add support for displaying exception causes when available (`exc_value.__cause__`)
- Add comprehensive unit tests covering all functionality including edge cases
- **src/flyte/_excepthook.py**: Updated `custom_excepthook` function to use proper traceback formatting and handle exception causes
- **tests/flyte/test_excepthook.py**: Added comprehensive test suite with 10 test cases covering all functionality

Improve exception handling in custom excepthook

---

examples/basics/dataframe_usage.py
examples/stress/long_running.py
examples/stress/long_running_reuse.py
examples/stress/rewrite_example.py
src/flyte/errors.py
src/flyte/io/_dataframe/dataframe.py
src/flyte/types/_type_engine.py

Before:
```
Error converting: Var:additional_properties, type:<class '_asyncio.Task'>, into:dict[str, float | None | str | bool | datetime.datetime | datetime.date | list[str]] | None, received_value <Task finished name='Task-36' coro=<TypeEngine.to_literal() done, defined at /opt/venv/lib/python3.12/site-packages/flyte/types/_type_engine.py:1082> exception=TypeTransformerFailedError("Value [{'c': ['hello'], 'algorithm': 'xgboost'}] is not of type dict[str, float | None | str | bool | datetime.datetime | datetime.date | list[str]] | None")>
```
After:
```
Error converting: Var:additional_properties, type:<class 'list'>, into:dict[str, float | None | str | bool | datetime.datetime | datetime.date | list[str]] | None, received_value [{'algorithm': 'xgboost', 'c': ['hello']}]
```
```python …
```

Improve error message for type engine
